### ISSUE TITLE
接口现在需要本地起吗

### ISSUE THREAD

**Issue by Yaob1990** [Armor-cn/nest-cloud-music-api#1]
好像需要本地起接口NeteaseCloudMusicApi？

里面的
 // 网易云提供的 Api 接口http://musicapi.leanapp.cn/
  // private readonly cloudMusicApi = 'https://music.aityp.com/';

好像不行...

**Comment by Yaob1990** [comment]
http://musicapi.leanapp.cn/

这个可以用

**Comment by Armor-cn** [comment]
@Yaob1990 卧槽，你为啥能看见？ 我不是设置成私有的吗？，这个我只是用nest的http模块调用了他node版的api，他底层数据是经过加密的，不知道她使用的什么算法，所以实现不了。

**Comment by Yaob1990** [comment]
> @Yaob1990 卧槽，你为啥能看见？ 我不是设置成私有的吗？，这个我只是用nest的http模块调用了他node版的api，他底层数据是经过加密的，不知道她使用的什么算法，所以实现不了。

我就是可以看见啊.....没有设置私有吧=-=
