### ISSUE TITLE
大佬呀，这个项目用到了7.0的哪些特性呢

### ISSUE THREAD

**Issue by Yaob1990** [Armor-cn/nest-cloud-music-api#2]
粗看了代码
没看明白哪些地方用到了7.0的特性，求大佬指点~

**Comment by Armor-cn** [comment]
就是把版本升级到7.0了，我这个项目还没有写底层，就是调用了一下接口。
7.0 就是优化了一些东西， 你可以看一下。
https://github.com/nestjs/nest/releases

**Comment by Yaob1990** [comment]
大佬还要写底层哇，期待~

**Comment by Armor-cn** [comment]
@Yaob1990  就是参数加一下密，CSRF伪造请求头 , 调用一下网易官方 API。哈哈哈。
